services:
  - type: web
    name: cr-mess-frontend
    env: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        fromService:
          name: cr-mess-backend
          type: web
          property: url

  - type: web
    name: cr-mess-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    disk:
      name: data
      mountPath: /mnt/data
      sizeGB: 1
    envVars:
      - key: ALLOWED_ORIGINS
        fromService:
          name: cr-mess-frontend
          type: web
          property: url
